[package]
name = "honeybee"
version = "0.4.4"

[dependencies]
base64 = "0.9"
log = "0.4"
env_logger = "0.5"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
failure = "0.1"
fallible-iterator = "0.1"
postgres = { version = "0.15" }
ssh2 = "0.3"
users = "0.7"
gif = "0.10"
