[package]
name = "mayfly"
version = "0.2.7"
edition = "2018"
default-run = "mayfly"

[dependencies]
argh = "0.1"
async-std = { version = "1.8", features = ["attributes"] }
chrono = "0.4"
env_logger = "0.8"
log = "0.4"
serde = { version = "1.0", features = ["derive"] }
thiserror = "1"
tide = "0.16"

[dependencies.zip]
version = "0.5"
default-features = false
features = ["deflate", "time"]
